{
 "title": "CSE474 Microservices Dashboard",
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{service}} {{status}}" }
   ]
  },
  {
   "title": "Latency p50/p95/p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m]) / rate(http_requests_total[1m])",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}