namespace: cse474-prod

commentsService:
  image: YOUR_DOCKERHUB_USERNAME/comments-service
  tag: latest
  replicas: 2
  port: 4000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

searchIndexService:
  image: YOUR_DOCKERHUB_USERNAME/search-index-service
  tag: latest
  replicas: 2
  port: 4001
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

postgres:
  commentsPassword: "password"
  searchPassword: "password"

kafka:
  brokers: "kafka:9092"
