apiVersion: v1
kind: Service
metadata:
  name: comments-service
  namespace: cse474-prod
spec:
  selector:
    app: comments-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
