apiVersion: v1
kind: Service
metadata:
  name: search-index-service
  namespace: cse474-prod
spec:
  selector:
    app: search-index-service
  ports:
    - port: 4001
      targetPort: 4001
  type: ClusterIP
